---
- name: WSL Ubuntu setup
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - vars.yml

  vars:
    run_bootstrap_scripts: false
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Ensure base directories exist in HOME
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop: "{{ directories }}"
      tags: [dirs]

    - name: Export environment variables system-wide
      ansible.builtin.include_tasks: tasks/env_simple.yml
      tags: [env]

    - name: apt repositories
      ansible.builtin.include_tasks: tasks/apt_repos.yml
      tags: [apt]

    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
      tags: [apt]

    - name: Wait for apt/dpkg locks to be released
      become: true
      ansible.builtin.shell: |
        if fuser /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/lib/apt/lists/lock >/dev/null 2>&1; then
          exit 1
        fi
        exit 0
      register: apt_locks
      retries: 60
      delay: 5
      until: apt_locks.rc == 0
      changed_when: false
      tags: [apt]

    - name: Install apt packages
      become: true
      ansible.builtin.apt:
        name: "{{ apt_packages }}"
        state: present
      tags: [apt]

    - name: Install pipx packages
      ansible.builtin.include_tasks: tasks/pipx.yml
      tags: [pipx]

    - name: Ensure /etc/shells includes zsh
      become: true
      ansible.builtin.lineinfile:
        path: /etc/shells
        line: /usr/bin/zsh
        state: present
        create: no
      tags: [zsh, shell]

    - name: Set zsh as default shell for current user
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh
      tags: [zsh, shell]

    - name: Ensure .zshrc contains a managed block for custom aliases
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        create: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK: Custom Aliases"
        block: |
          {% for alias_name, alias_command in shell_aliases.items() %}
          alias {{ alias_name }}='{{ alias_command | replace("'", "'" ~ '"' ~ "'" ~ '"' ~ "'") }}'
          {% endfor %}
      tags: [aliases, shell]

    - name: Git configuration
      ansible.builtin.include_tasks: tasks/git.yml
      tags: [git]

    - name: Terraform
      ansible.builtin.include_tasks: tasks/terraform.yml
      tags: [terraform, scripts]

    - name: TFLint
      ansible.builtin.include_tasks: tasks/tflint.yml
      tags: [tflint, scripts]

    - name: Infracost
      ansible.builtin.include_tasks: tasks/infracost.yml
      tags: [infracost, scripts]

    - name: Kubectl
      ansible.builtin.include_tasks: tasks/kubectl.yml
      tags: [kubectl, scripts]

    - name: Helm
      ansible.builtin.include_tasks: tasks/helm.yml
      tags: [helm, scripts]

    - import_tasks: tasks/vscode_extensions.yml
      tags: [vscode]
