- name: Install infracost (bootstrap-only)
  ansible.builtin.shell: |
    curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
  args:
    executable: /bin/bash
  changed_when: false
  register: infracost_check
  failed_when: infracost_check.rc not in [0]
  when: run_bootstrap_scripts | bool
  tags: [bootstrap, infracost, scripts]
